#!/usr/bin/env python3
"""Helper script to build the OCRA Qt GUI on Windows or macOS."""
from __future__ import annotations

import argparse
import platform
import shutil
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent
ENTRYPOINT = PROJECT_ROOT / "ocr_gui.py"
DATA_DIR = PROJECT_ROOT / "ocr_ai"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Create a packaged build of the OCRA GUI with PyInstaller.")
    parser.add_argument(
        "--platform",
        choices=["auto", "windows", "mac"],
        default="auto",
        help="Override the target platform; defaults to the current host.",
    )
    parser.add_argument("--clean", action="store_true", help="Remove previous build artifacts before packaging.")
    parser.add_argument(
        "--icon",
        type=Path,
        help="Optional path to an .ico (Windows) or .icns (macOS) icon file to embed in the bundle.",
    )
    parser.add_argument(
        "--bundle-id",
        default="com.example.ocra",
        help="Bundle identifier to use on macOS builds (ignored on Windows).",
    )
    parser.add_argument(
        "--pyinstaller-args",
        nargs=argparse.REMAINDER,
        help="Extra arguments forwarded to PyInstaller after the autogenerated ones.",
    )
    return parser.parse_args()


def detect_platform(override: str) -> str:
    if override in {"windows", "mac"}:
        return override

    current = platform.system().lower()
    if current == "windows":
        return "windows"
    if current == "darwin":
        return "mac"
    msg = "Unsupported host platform; specify --platform windows|mac explicitly."
    raise RuntimeError(msg)


def ensure_prerequisites() -> None:
    if not ENTRYPOINT.exists():
        msg = f"Entry script not found: {ENTRYPOINT}"
        raise FileNotFoundError(msg)
    if not DATA_DIR.exists():
        msg = f"Data directory not found: {DATA_DIR}"
        raise FileNotFoundError(msg)

    try:
        __import__("PyInstaller")
    except ModuleNotFoundError:
        print("PyInstaller not found; installing it now...")
        subprocess.check_call([sys.executable, "-m", "pip", "install", "pyinstaller"])


def clean_previous_outputs() -> None:
    for folder in ("build", "dist"):
        shutil.rmtree(PROJECT_ROOT / folder, ignore_errors=True)


def build_command(target: str, icon: Path | None, bundle_id: str, extra_args: list[str] | None) -> list[str]:
    sep = ":" if target == "mac" else ";"
    data_arg = f"{DATA_DIR.resolve()}{sep}ocr_ai"

    cmd = [
        sys.executable,
        "-m",
        "PyInstaller",
        str(ENTRYPOINT),
        "--name",
        "OCRA",
        "--noconsole",
        "--add-data",
        data_arg,
    ]

    if target == "mac":
        cmd.extend(["--osx-bundle-identifier", bundle_id])
    if icon:
        cmd.extend(["--icon", str(icon.resolve())])
    if extra_args:
        cmd.extend(extra_args)

    return cmd


def main() -> None:
    args = parse_args()
    target = detect_platform(args.platform)
    ensure_prerequisites()

    if args.clean:
        clean_previous_outputs()

    cmd = build_command(target, args.icon, args.bundle_id, args.pyinstaller_args)
    print("Running:", " ".join(cmd))
    subprocess.check_call(cmd)

    if target == "mac":
        print("macOS build ready under dist/OCRA.app")
    else:
        print("Windows build ready under dist/OCRA/OCRA.exe")


if __name__ == "__main__":
    main()
